### PR TITLE
Add support for new achitecture (Turbo module)

### PR DESCRIPTION
**Pull request by zabojad**
Hi there ! 

Here is a PR adding support for the new architecture. It's still compatible with the old one though...

I've added a note to the README and bumped the package.json version to 1.2.0...

### CODE REVIEW

**Comment by zabojad** [comment]
Hi there @sayem314 ! Could you please have a look and eventually merge it?

**Comment by sayem314** [comment]
Hi @zabojad,

Thank you for the pull request and the code changes. I've reviewed the code and it looks good so far. However, before merging and publishing, I would like to ensure that the code has been tested on a real device. Could you please confirm if you have tested the changes on a real device? 

Once we have confirmation of successful testing, I'll be more than happy to proceed with merging and publishing the changes.

Thank you!

**Comment by sayem314** [comment]
Also can you please fix formatting here.
https://github.com/zabojad/react-native-keep-awake/blob/2e7783a68802209a4f3dd4792c0e6248d7022d53/android/build.gradle#L7

**Comment by sayem314** [comment]
And also remove `Log.v*` from `android/src/main/java/com/sayem/keepawake/KCKeepAwakeImpl.java`

**Comment by zabojad** [comment]
> Thank you for the pull request and the code changes. I've reviewed the code and it looks good so far. However, before merging and publishing, I would like to ensure that the code has been tested on a real device. Could you please confirm if you have tested the changes on a real device?

Yes, I've tested on both iPhone and Android phone, and on both RN 68 and RN 71 with and without new architecture activated...

**Comment by zabojad** [comment]
I've just pushed a new commit following your remarks...

**Comment by sayem314** [comment]
Thank you very much. Much appreciated :)

**Pull request merged**
